<h2>Consultas:</h2>

<li><a href='index/consultar-membros-lab'>
1) Qual o nome dos membros do laboratório?</a></li>
<li><a href='index/consultar-prof-colaboradores-lab'>
2) Quais os nomes dos professores colaboradores do laboratório?</a></li>
<li><a href='index/consultar-projetos-lab'>
3) Quais os projetos em execução no laboratório?</a></li>
<li><a href='index/consultar-membros-nao-ephenology'>
4) Quais os membros do laboratório que não compõe a equipe do projeto "e-phenology"?</a></li>
<li><a href='index/consultar-coordenador-projetos'>
5) Qual o coordenador dos projetos conduzidos no laboratório entre o período 
de abril de 2009 a julho de 2012?</a></li>
<li><a href='index/consultar-inst-financia-proj'>
6) Qual instituição financia o projeto "e-phenology"?</a></li>
<li><a href='index/consultar-orientador-jurandy'>
7) Quem orientou o mestrado de Jurandy Almeida?</a></li>
<li><a href='index/consultar-orientados-profarocha-defenderam'>
8) Quais alunos orientados pelo	Prof. Anderson Rocha defenderam	em 2012?</a></li>
<li><a href='index/consultar-subprojetos-ephenology'>
9) Quais os nomes dos subprojetos do projeto "e­-phenology"?</a></li>
<li><a href='index/consultar-contribuicoes-ephenology'>
10) Quais as contribuições associadas ao projeto "e­-phenology"?</a></li>
<li><a href='index/consultar-qualis-internacionais'>
11) Quais os artigos com classificação Qualis A1 foram publicados em 2012 
em periódicos internacionais?</a></li>
<li><a href='index/consultar-artigos-profarocha'>
12) Quais os artigos publicados pelo Prof. Anderson Rocha em 2011?</a></li>
<li><a href='index/consultar-alunos-estg-sanduiche'>
13) Quais alunos estavam em estágio sanduíche em 2010?</a></li>
<li><a href='index/consultar-dados-jefersson'>
14) Quem era o supervisor e	qual agência financiou o estágio sanduíche 
do aluno Jefersson Alex dos Santos?</a></li>
<li><a href='index/consultar-qtde-bancas-helio'>
15) Quantas vezes o Prof. Helio Pedrini participou de bancas de doutorado 
de alunos do laboratório?</a></li>
<li><a href='index/consultar-patentes-profarocha'>
16) Qual o título das patentes registradas pelo Prof.Anderson Rocha?</a></li>
<li><a href='index/consultar-data-palestra'>
17) Quando a palestra "Reasoning for Complex Data" foi apresentada?</a></li>
<li><a href='index/consultar-publicacoes-doutorandos'>
18) Quais as publicações associadas a alunos de doutorado do laboratório?</a></li>
<li><a href='index/consultar-proj-mais-publicado'>
19) Qual projeto gerou mais publicações em conferências?
Liste todos os artigos publicados.</a></li>
<li><a href='index/consultar-prof-fapesp-nao-rtorres'>
20) Selecione o nome dos professores que trabalham em todos os projetos 
do laboratório financiados pela	FAPESP e que não trabalham em nenhum 
projeto coordenado pelo Prof. Ricardo Torres.</a></li>