<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="pt-BR">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />				
		<title>Sistema de Laboratório</title>
	</head>
	 
	<body>
	
	<table width="80%">
		<tr >
			
			<td id="topo">
				<h1>
						Sistema de Laboratório
				</h1>
				<ul>
					<?php echo $this->layout()->content ?>
				</ul>
			</td>
		</tr>
		<tr >
			<td colspan="2" id="rodape">
				<br><b>Grupo 03:</b><br> 
					Fernando Luis de Oliveira Costa RA: 091188<br> 
					Waldir Rodrigues de Almeida RA: 106991
			</td>
		</tr>
	</table>
	</body>
</html>